
CREATE TABLE CREDITACCOUNT  (
  ID BIGINT NOT NULL PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  RESERVED DECIMAL(18,4) ,
  LASTBILLID BIGINT ,
  BALANCE DECIMAL(18,4) ,
  BILLINGTYPE VARCHAR(20) ,
  CARDNO VARCHAR(50) ,
  CREATEDTIMESTAMP TIMESTAMP ,
  CREDITLIMIT DECIMAL(18,4) ,
  CUSTOMERID BIGINT ,
  ISSUEDATE TIMESTAMP ,
  MEMO VARCHAR(255) ,
  NEXTBILLDATE DATE ,
  NEXTBILLBATCHID INTEGER NOT NULL ,
  PERTRXLIMITMAX DECIMAL(18,4) ,
  PERTRXLIMITMIN DECIMAL(18,4) ,
  MODIFIEDTIMESTAMP TIMESTAMP ,
  NEXTBILLDETAILID INTEGER NOT NULL ,
  PASSWORD VARCHAR(255) ,
  STATUS VARCHAR(20) ,
  SUPPORTAIRCUSNUM VARCHAR(2400) ,
  NOINTERESTDAYS INTEGER ,
  LATEFEEPERCENTAGE DECIMAL(18,2) ,
  LATEFEE DECIMAL(18,2) ,
  DAYSPASTDUE INTEGER  DEFAULT 0 ,
  FREQUENCYPASTDUE INTEGER  DEFAULT 0 ,
  PASTDUEBILL BIGINT ,
  SUMBILLTYPE VARCHAR(20)  DEFAULT 'FIX' ,
  SUSPENDTIME BIGINT ,
  ACTIVESTATUS VARCHAR(15)  DEFAULT 'ACTIVE' ,
  CUSTOMERFEATURE VARCHAR(50) ,
  DAILYINTERESTRATE DECIMAL(18,2) ,
  BILLCYCLE INTEGER )ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

CREATE TABLE SERVICEPRICE  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  PRICETYPE VARCHAR(50) ,
  MASTERVALIDDATE TIMESTAMP ,
  MASTEREXPIREDATE TIMESTAMP ,
  SLAVEVALIDDATE TIMESTAMP ,
  SLAVEEXPIREDATE TIMESTAMP ,
  SERVICEPRICEGROUPTYPE VARCHAR(50) ,
  CUSTOMER_ID BIGINT ,
  FRP_ID BIGINT ,
  MASTERFEE_ID BIGINT ,
  SLAVEFEE_ID BIGINT ) ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;



CREATE TABLE MOBILEBE.SERVICEPRICE  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  PRICETYPE VARCHAR(50) ,
  MASTERVALIDDATE TIMESTAMP ,
  MASTEREXPIREDATE TIMESTAMP ,
  SLAVEVALIDDATE TIMESTAMP ,
  SLAVEEXPIREDATE TIMESTAMP ,
  SERVICEPRICEGROUPTYPE VARCHAR(50) ,
  CUSTOMER_ID BIGINT ,
  FRP_ID BIGINT ,
  MASTERFEE_ID BIGINT ,
  SLAVEFEE_ID BIGINT ) ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;


CREATE TABLE SERVICEPRICERULE  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  RULEEXPRESSION VARCHAR(1024) ,
  RULEDESCRIPTION VARCHAR(255) ,
  RULENAME VARCHAR(255) ,
  EXPRESSIONTYPE VARCHAR(50) ,
  CUSTOMERID BIGINT ,
  CUSTOMERPRIVATE SMALLINT NOT NULL  DEFAULT 0 ,
  SRCFEEEXPRESSION VARCHAR(1000) ,
  EXTFEEEXPRESSION VARCHAR(1000) )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;



CREATE TABLE SETTLEMENTINFO  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  RESERVEDAYS INTEGER NOT NULL ,
  MINAMOUNT DECIMAL(18,4) ,
  LASTSETTLEDATE TIMESTAMP ,
  CYCLETYPE VARCHAR(20) ,
  CYCLEDATA VARCHAR(255) ,
  NEXTBATCHID BIGINT NOT NULL ,
  MAXAMOUNT DECIMAL(18,4) ,
  MAXDAYS INTEGER NOT NULL ,
  SETTLETYPE VARCHAR(20) ,
  CUSTOMER_ID BIGINT ,
  LOCALACCOUNT_ID BIGINT NOT NULL ,
  BANKACCOUNT_ID BIGINT ,
  LASTPROCESSDATE TIMESTAMP ,
  VALID SMALLINT ,
  LIMITOFREMITFEE DECIMAL(18,4) NOT NULL ,
  NEEDREMITFEE SMALLINT NOT NULL ,
  MAXACTHISID BIGINT ,
  MINACTHISID BIGINT ,
  MEMO VARCHAR(255) ,
  STATUS VARCHAR(20)  DEFAULT 'SETTLEABLE' ,
  REALTIMEUPDATE INTEGER  DEFAULT 0 ,
  LASTSETTLERECORDID BIGINT ,
  NEEDINVOICE SMALLINT ,
  INVOICEMODE VARCHAR(20) ,
  INVOICETITLE VARCHAR(160) ,
  INVOICEMESSAGE VARCHAR(255) ,
  ISNEEDANOTHERSETTLE SMALLINT ,
  LASTCHECKDATE TIMESTAMP ,
  COMMENTDESCRIPTION VARCHAR(255) ,
  MONTHBEGINSETTLE SMALLINT  DEFAULT 0 ,
  MONTHENDSETTLE SMALLINT  DEFAULT 0 )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;




CREATE TABLE EMPLOYEE  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  ACTIVE SMALLINT ,
  CREATEDATE TIMESTAMP ,
  LOGINUSERID BIGINT ,
  NAME VARCHAR(100) ,
  RANK INTEGER ,
  DESCRIPTION VARCHAR(300) ,
  COMPANY_ID BIGINT ,
  INDEP_ID BIGINT ,
  SUPERIOR_ID BIGINT ,
  POSITION_ID BIGINT ,
  PRODUCTLINE VARCHAR(20) ,
  EMAIL VARCHAR(50) ,
  EMPLOYEETEAM_ID BIGINT ,
  ENTRYTIME DATE ,
  BUSINESSCAT VARCHAR(20) )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;


CREATE TABLE CUSTOMERAPTITUDEADUIT  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  CUSTOMERID BIGINT ,
  AUDITSTATUS VARCHAR(20) ,
  CUSTOMERTYPE VARCHAR(20) ,
  APTITUDESTATUS VARCHAR(20) ,
  AUDITORNAME VARCHAR(255) ,
  AUDITPASSTIME TIMESTAMP ,
  DELAYTIMES INTEGER ,
  RECEIVEAPTITUDE TIMESTAMP ,
  REGTIME TIMESTAMP ,
  REMAINDAY INTEGER ,
  RETICULATIONAUDITSTATUS VARCHAR(20) ,
  OPTDESC VARCHAR(255) )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;


CREATE TABLE RETURNFEECUSTOMERINFO  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  CUSTOMERID BIGINT ,
  CUSTOMERNUMBER VARCHAR(30) ,
  CUSTOMERNAME VARCHAR(200) ,
  MINLIMIT DECIMAL(18,4) ,
  MAXLIMIT DECIMAL(18,4) ,
  BANKID VARCHAR(50) ,
  BANKACCOUNTNAME VARCHAR(200) ,
  BANKACCOUNTID VARCHAR(50) ,
  PROVINCE VARCHAR(100) ,
  BANKBRANCH VARCHAR(200) ,
  BANKCARDTYPE VARCHAR(20) ,
  CITY VARCHAR(100) ,
  OPERATORID BIGINT ,
  STATUS VARCHAR(20) ,
  CREATETIME TIMESTAMP ,
  DESCRIPTION VARCHAR(500) ,
  MAIL VARCHAR(40) ,
  ISINVOICE INTEGER ,
  IDCARD VARCHAR(30) ,
  AGENTSALESNAME VARCHAR(50) )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;



CREATE TABLE RETURNFEERELATIONSHIP  (
  ID BIGINT NOT NULL  PRIMARY KEY,
  OPTIMISTIC INTEGER ,
  FROMCUSTOMERID BIGINT NOT NULL ,
  TOINFOID BIGINT NOT NULL ,
  RETURNFEETYPE VARCHAR(20) ,
  COMPUTETYPE VARCHAR(20) ,
  COMPUTABLE INTEGER ,
  COMPUTECOUNT INTEGER ,
  OPERATORID BIGINT ,
  EXPRESSION VARCHAR(2000) ,
  STARTDATE DATE ,
  ENDDATE DATE ,
  COMPUTEFROMDATE DATE ,
  COMPUTETODATE DATE ,
  CREATETIME TIMESTAMP ,
  COMPUTEHISTORY VARCHAR(1000) ,
  LATESTCOMPUTETIME TIMESTAMP ,
  LASTCOMPUTETIME TIMESTAMP ,
  LASTCOMPUTEFROMDATE DATE ,
  LASTCOMPUTETODATE DATE ,
  STATUS VARCHAR(20) ,
  SALESNAME VARCHAR(50) ,
  DESCRIPTION VARCHAR(500) ,
  FEEMEMO VARCHAR(2000) ,
  BIZCOMPUTETYPE VARCHAR(20) ,
  ADJUSTAMOUNTAFTERCOMPUTE DECIMAL(18,4)  DEFAULT 0 ,
  AUTOCOMPUTE SMALLINT  DEFAULT 0 ,
  ADDFLAG SMALLINT  DEFAULT 0 ,
  FINANCELASTFROMDATE DATE ,
  FINANCELASTTODATE DATE ,
  FINANCELASTCOMPUTETIME TIMESTAMP ,
  RETURNFEERELATIONSHIPTYPE VARCHAR(20) ,
  COMPUTESTATUS INTEGER ,
  FINANCECOMPUTESTATUS INTEGER ,
  DEDUCTFLAG INTEGER ,
  DEDUCTAMOUNT DECIMAL(18,4) ,
  CLOSEREASON VARCHAR(50) ,
  FINANCETHELASTCOMPUTEFROMDATE DATE ,
  FINANCETHELASTCOMPUTETODATE DATE ,
  FINANCETHELASTCOMPUTETIME TIMESTAMP )   ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;







CREATE TABLE PROFILE  (
		  ID BIGINT NOT NULL PRIMARY KEY, 
		  OPTIMISTIC INTEGER , 
		  PFTYPE VARCHAR(20) , 
		  NAME VARCHAR(50) , 
		  VALUE VARCHAR(900) , 
		  CUSTOMER_ID BIGINT )  ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;



CREATE TABLE EMPLOYEE2CUSTOMER  (
		  EMP_ID BIGINT NOT NULL PRIMARY KEY , 
		  CUST_ID BIGINT NOT NULL )  ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

CREATE TABLE CUSTOMERDOCINFO  (
		  ID BIGINT NOT NULL PRIMARY KEY, 
		  OPTIMISTIC INTEGER , 
		  CUSTOMERNUMBER VARCHAR(255) , 
		  DOCUMENTNAME VARCHAR(255) , 
		  DOCUMENTNUMBER VARCHAR(255) , 
		  AVAILABDATA TIMESTAMP , 
		  CONTRAID BIGINT , 
		  DOCSTATUS SMALLINT NOT NULL , 
		  DESCRIPTION VARCHAR(255) )  ENGINE=myisam  DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
